### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheOdd** [lantay/mapmycode#2]
## Definitely:

- [ ] Flesh out concretes on what we actually want the package to do. Specifics and possible implementation methods included.
- [ ] Function to scan current document or selection.
- [ ] Function to interpret scanned text and return value based on a set of conditions/rules.
- [ ] Display returned value in tooltip-ish kind of view next to line.

## Maybe:

- [ ] Different hotkey/triggers customization/binding.
- [ ] Introduce a method to dynamically recognize what constitutes a variable instead of hardcoding in keywords.
- [ ] Allow for configuration files for easier customization and possible keyword integration for different projects. (Allows for user to customize without modifying core code.)
- [ ] If above goal is implemented, make a function to handle customization files

***Any of the goals in here are subject to change as well as possibly adding new goals and removing current ones.***
